SeaORM/docs/04-basic-crud/02-insert.md, SeaORM/docs/04-basic-crud/03-update.md, SeaORM/docs/06-write-test/02-mock.md, SeaORM/src/components/HomepageExample.js
Update docs for SeaQL/sea-orm#132
=> Edit update and insert docs

SeaORM/blog/2021-10-15-whats-new-in-0.3.0.md, SeaORM/docs/02-install-and-config/03-connection.md
=> 0.3.0 Docs

SeaORM/versioned_docs/version-0.7.x/05-migration/01-setting-up-migration.md, SeaORM/versioned_docs/version-0.7.x/05-migration/02-writing-migration.md, SeaORM/versioned_docs/version-0.7.x/05-migration/03-running-migration.md
- Closes 
- 
- Dependents:
- 
- Improves documentation on migrations
- Fixes some typos
- Improves some wording (only makes it "sound" better, let me know if anything is unnecessary here)
- Links "Writing Migration" from the "Migration Crate" subheading of "Set up migration". I found this confusing initially as the snippet doesn't how to write a migration when there's no entities defined. I thought "Next section" meant the next sub-heading. This change should prevent the confusion.
=> Improve wording in migration docs and link "Writing Migration" from set up

StarfishQL/docusaurus.config.js, StarfishQL/package-lock.json, StarfishQL/package.json, StarfishQL/yarn.lock
=> StarfishQL: Upgrade docusaurus to 2.0.0-beta.22

.github/workflows/deploy.yml, build.sh, publish.sh
=> Build script

Blog/package-lock.json, Blog/package.json, Blog/yarn.lock, SeaORM/package-lock.json, SeaORM/package.json, SeaORM/yarn.lock, StarfishQL/package-lock.json, StarfishQL/package.json, StarfishQL/yarn.lock
[🎉 Docusaurus 2.0 is out!️ 🥳](https://docusaurus.io/blog/2022/08/01/announcing-docusaurus-2.0)
=> Bump Docusaurus version to v2

Blog/blog/2022-07-23-whats-new-in-seaquery-0.26.0.md, Blog/blog/2022-08-05-whats-new-in-seaquery-0.26.0.md, docs/index.html
- Closes https://github.com/SeaQL/seaql.github.io/issues/42
=> issues-42 Whats new in SeaQuery 0.26

Blog/blog/2022-09-16-introducing-seaography.md
=> [blog] introducing Seaography - A GraphQL framework and code generator for SeaORM

SeaORM/versioned_docs/version-0.9.x/03-migration/02-writing-migration.md
=> Add link for create_*_from_entity

Blog/blog/2022-09-27-getting-started-with-seaography.md
=> [blog] Getting Started with Seaography

Blog/blog/2021-09-20-introducing-sea-orm.md
I haven't been using this name in a looooong time - thanks :)
Alternatively I'd be fine with just removing me from the list, after all my contribution was rather minimal and I stopped using sea-query shortly after.
=> fix my name

Blog/blog/2022-11-09-toggle-stacked-download-graph-in-crates-io.md
=> Toggle Stacked Download Graph in crates.io

SeaORM/docs/04-generate-entity/02-entity-structure.md, SeaORM/versioned_docs/version-0.10.x/04-generate-entity/02-entity-structure.md
- Closes N/A
- N/A
- Dependents:
- N/A
- Related Discord conversations:
- https://discord.com/channels/873880840487206962/900758376164757555/1040271560994467920
Rendered:
N/A
N/A
N/A
=> feat: Add a note about keeping Relation and ActiveModelBehavior

SeaORM/docs/05-basic-crud/05-delete.md, SeaORM/src/components/HomepageExample.js, SeaORM/versioned_docs/version-0.10.x/05-basic-crud/05-delete.md
- Continue https://github.com/SeaQL/seaql.github.io/pull/67
=> Cont: Added cast to ActiveModel to make delete work (#67)

Blog/blog/2022-10-31-whats-new-in-seaquery-0.27.0.md
- Closes https://github.com/SeaQL/sea-query/issues/545
- Fix example
=> Fix example

Blog/blog/2023-01-23-introducing-otter-sql.md
=> Introducing OtterSQL

Blog/blog/2023-01-28-internship-at-seaql.md
@shpun817 @karatakis still a draft though
=> Internship @ SeaQL

.github/workflows/deploy.yml
=> [CI] downgrade to Node v16

SeaORM/docs/04-generate-entity/02-entity-structure.md, SeaORM/docs/04-generate-entity/04-enumeration.md
- SeaQL/sea-orm#2160
- https://github.com/SeaQL/sea-orm/pull/2170
=> Add Documentation For New Attributes SeaQL/sea-orm#2160

SeaORM/versioned_docs/version-1.1.x/02-install-and-config/01-database-and-async-runtime.md
Changed "for your convenient" to "for your convenience."
=> Small grammar correction

SeaORM/docs/05-basic-crud/02-select.md
nothing much other than thank you 😃
=> end line with semicolon in example
